# Generated by Django 4.0.4 on 2022-09-23 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='Signup',
        ),
    ]
