# Generated by Django 4.0.4 on 2022-09-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_login_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='mails',
        ),
        migrations.AddField(
            model_name='signup',
            name='phoneno',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
