# Generated by Django 4.0.4 on 2022-09-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_signup_mails_signup_phoneno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='login',
        ),
    ]
